name: Deploy to Firebase

on:
  push:
    branches:
      - main  # This means it will trigger on every push to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This defines the environment the job will run in

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set environment variables (secrets stored in GitHub)
      - name: Set Firebase environment variables
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> $GITHUB_ENV

      # Install Firebase CLI (if you're deploying to Firebase)
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Authenticate with Firebase
      - name: Firebase Login
        run: firebase login --token ${{ secrets.FIREBASE_CI_TOKEN }}

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
